<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\MiniAtraShared\MiniAtraShared.projitems" Label="Shared" />
  <Import Project="..\..\csproj_common" />

  <PropertyGroup>
    <EnableHarmony>true</EnableHarmony>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.4.0</Version>
    <Name>Less Mini Shipping Bin</Name>
    <Description>Lets you make the mini shipping bin bigger.</Description>
    <UpdateKeys>Nexus:10959</UpdateKeys>
  </PropertyGroup>

  <PropertyGroup>
    <TranslationClassBuilder_AddGetByKey>true</TranslationClassBuilder_AddGetByKey>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="StardewValley" />
    <Using Include="StardewModdingAPI" />
    <Using Include="JetBrains.Annotations" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Alias="NotNullAttribute" Include="System.Diagnostics.CodeAnalysis.NotNullAttribute" />
    <Using Alias="Object" Include="System.Object" />
    <Using Alias="SObject" Include="StardewValley.Object" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="JetBrains.Annotations" Version="2023.3.0" />
  </ItemGroup>
</Project>