#!/usr/bin/env python3.11

import markdown
import tomllib
from pathlib import Path;
import re

endtags = re.compile(r"</h\d>")
endlists = re.compile(r"</[ou]l>")
urls = re.compile(r'<a href=\"(http.*?)\">(.*?)</a>')
relativeurls = re.compile(r'<a href=\"(.*?)\">(.*?)</a>')

substitutions = {
    "<h1>": "[size=6]",
    "<h2>": "[size=5]",
    "<h3>": "[size=4]",
    "<h4>": "[size=4]",
    "<ol>": "[list=1]",
    "<ul>": "[list]",
    "<li>": "[*]",
    "</li>" : "",
    "<p>": "",
    "</p>": "\n",
    "<code>": "[font=Courier New]",
    "</code>": "[/font]",
    "<strong>": "[b]",
    "</strong>": "[/b]",
}

p = Path('.')

for x in p.glob('**/README.md'):
    if x.parent.name.endswith('docs'):
        continue
    print("Processing: " + str(x))
    with open(x, "r") as input_file:
        html = markdown.markdown(input_file.read())
        for k,v in substitutions.items():
            html = html.replace(k,v)
        html = endtags.sub("[/size]", html)
        html = endlists.sub("[/list]", html)
        html = urls.sub(r"[url=\1]\2[/url]", html)
        
        relativeurl = "/".join(x.parent.parts)
        html = relativeurls.sub(r"[url=https://github.com/atravita-mods/StardewMods/blob/main/" + relativeurl + r"/\1]\2[/url]", html)
        
        #create output file. 
        with open(x.with_suffix(".bbcode"), "w") as output_file:
            output_file.write(html)